workspace(name = "org_tensorflow")

local_repository(
    name = "io_bazel_rules_closure",
    path = "tensorflow_third_party/io_bazel_rules_closure"
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()

load("//tensorflow:workspace.bzl", "check_version", "tf_workspace")

# We must check the bazel version before trying to parse any other BUILD files,
# in case the parsing of those build files depends on the bazel version we
# require here.
check_version("0.4.2")

# Uncomment and update the paths in these entries to build the Android demo.
#android_sdk_repository(
#    name = "androidsdk",
#    path = "tensorflow_third_party/androidsdk"
#    build_tools_version = "25.0.1",
#    # Replace with path to Android SDK on your system
#    path = "<PATH_TO_SDK>",
#)
#
#android_ndk_repository(
#    name="androidndk",
#    path="<PATH_TO_NDK>",
#    api_level=14)

# Please add all new TensorFlow dependencies in workspace.bzl.
tf_workspace()

local_repository(
  name = "inception5h",
  path = "tensorflow_third_party/inception5h"
  
)

local_repository(
  name = "mobile_multibox",
  path = "tensorflow_third_party/mobile_multibox"
  
)

local_repository(
  name = "stylize",
  path = "tensorflow_third_party/stylize"
)

# TENSORBOARD_BOWER_AUTOGENERATED_BELOW_THIS_LINE_DO_NOT_EDIT

local_repository(
  name = "d3",
  path = "tensorflow_third_party/d3"
  
  
)

local_repository(
  name = "dagre",
  path = "tensorflow_third_party/dagre"
  
  
)

local_repository(
  name = "es6_promise",
  path = "tensorflow_third_party/es6_promise"
  
  
)

local_repository(
  name = "font_roboto",
  path = "tensorflow_third_party/font_roboto"
  
  
)

local_repository(
  name = "graphlib",
  path = "tensorflow_third_party/graphlib"
  
  
)

local_repository(
  name = "iron_a11y_announcer",
  path = "tensorflow_third_party/iron_a11y_announcer"
  
  
)

local_repository(
  name = "iron_a11y_keys_behavior",
  path = "tensorflow_third_party/iron_a11y_keys_behavior"
  
  
)

local_repository(
  name = "iron_ajax",
  path = "tensorflow_third_party/iron_ajax"
  
  
)

local_repository(
  name = "iron_autogrow_textarea",
  path = "tensorflow_third_party/iron_autogrow_textarea"
  
  
)

local_repository(
  name = "iron_behaviors",
  path = "tensorflow_third_party/iron_behaviors"
  
  
)

local_repository(
  name = "iron_checked_element_behavior",
  path = "tensorflow_third_party/iron_checked_element_behavior"
  
  
)

local_repository(
  name = "iron_collapse",
  path = "tensorflow_third_party/iron_collapse"
  
  
)

local_repository(
  name = "iron_dropdown",
  path = "tensorflow_third_party/iron_dropdown"
  
  
)

local_repository(
  name = "iron_fit_behavior",
  path = "tensorflow_third_party/iron_fit_behavior"
  
  
)

local_repository(
  name = "iron_flex_layout",
  path = "tensorflow_third_party/iron_flex_layout"
  
  
)

local_repository(
  name = "iron_form_element_behavior",
  path = "tensorflow_third_party/iron_form_element_behavior"
  
  
)

local_repository(
  name = "iron_icon",
  path = "tensorflow_third_party/iron_icon"
  
  
)

local_repository(
  name = "iron_icons",
  path = "tensorflow_third_party/iron_icons"
  
  
)

local_repository(
  name = "iron_iconset_svg",
  path = "tensorflow_third_party/iron_iconset_svg"
  
  
)

local_repository(
  name = "iron_input",
  path = "tensorflow_third_party/iron_input"
  
  
)

local_repository(
  name = "iron_list",
  path = "tensorflow_third_party/iron_list"
  
  
)

local_repository(
  name = "iron_menu_behavior",
  path = "tensorflow_third_party/iron_menu_behavior"
  
  
)

local_repository(
  name = "iron_meta",
  path = "tensorflow_third_party/iron_meta"
  
  
)

local_repository(
  name = "iron_overlay_behavior",
  path = "tensorflow_third_party/iron_overlay_behavior"
  
  
)

local_repository(
  name = "iron_range_behavior",
  path = "tensorflow_third_party/iron_range_behavior"
  
  
)

local_repository(
  name = "iron_resizable_behavior",
  path = "tensorflow_third_party/iron_resizable_behavior"
  
  
)

local_repository(
  name = "iron_scroll_target_behavior",
  path = "tensorflow_third_party/iron_scroll_target_behavior"
  
  
)

local_repository(
  name = "iron_selector",
  path = "tensorflow_third_party/iron_selector"
  
  
)

local_repository(
  name = "iron_validatable_behavior",
  path = "tensorflow_third_party/iron_validatable_behavior"
  
  
)

local_repository(
  name = "lodash",
  path = "tensorflow_third_party/lodash"
  
  
)

local_repository(
  name = "neon_animation",
  path = "tensorflow_third_party/neon_animation"
  
  
)

local_repository(
  name = "numericjs_numeric_min_js",
  path = "tensorflow_third_party/numericjs_numeric_min_js"
)

local_repository(
  name = "paper_behaviors",
  path = "tensorflow_third_party/paper_behaviors"
  
  
)

local_repository(
  name = "paper_button",
  path = "tensorflow_third_party/paper_button"
  
  
)

local_repository(
  name = "paper_checkbox",
  path = "tensorflow_third_party/paper_checkbox"
  
  
)

local_repository(
  name = "paper_dialog",
  path = "tensorflow_third_party/paper_dialog"
  
  
)

local_repository(
  name = "paper_dialog_behavior",
  path = "tensorflow_third_party/paper_dialog_behavior"
  
  
)

local_repository(
  name = "paper_dialog_scrollable",
  path = "tensorflow_third_party/paper_dialog_scrollable"
  
  
)

local_repository(
  name = "paper_dropdown_menu",
  path = "tensorflow_third_party/paper_dropdown_menu"
  
  
)

local_repository(
  name = "paper_header_panel",
  path = "tensorflow_third_party/paper_header_panel"
  
  
)

local_repository(
  name = "paper_icon_button",
  path = "tensorflow_third_party/paper_icon_button"
  
  
)

local_repository(
  name = "paper_input",
  path = "tensorflow_third_party/paper_input"
  
  
)

local_repository(
  name = "paper_item",
  path = "tensorflow_third_party/paper_item"
  
  
)

local_repository(
  name = "paper_listbox",
  path = "tensorflow_third_party/paper_listbox"
  
  
)

local_repository(
  name = "paper_material",
  path = "tensorflow_third_party/paper_material"
  
  
)

local_repository(
  name = "paper_menu",
  path = "tensorflow_third_party/paper_menu"
  
  
)

local_repository(
  name = "paper_menu_button",
  path = "tensorflow_third_party/paper_menu_button"
  
  
)

local_repository(
  name = "paper_progress",
  path = "tensorflow_third_party/paper_progress"
  
  
)

local_repository(
  name = "paper_radio_button",
  path = "tensorflow_third_party/paper_radio_button"
  
  
)

local_repository(
  name = "paper_radio_group",
  path = "tensorflow_third_party/paper_radio_group"
  
  
)

local_repository(
  name = "paper_ripple",
  path = "tensorflow_third_party/paper_ripple"
  
  
)

local_repository(
  name = "paper_slider",
  path = "tensorflow_third_party/paper_slider"
  
  
)

local_repository(
  name = "paper_spinner",
  path = "tensorflow_third_party/paper_spinner"
  
  
)

local_repository(
  name = "paper_styles",
  path = "tensorflow_third_party/paper_styles"
  
  
)

local_repository(
  name = "paper_tabs",
  path = "tensorflow_third_party/paper_tabs"
  
  
)

local_repository(
  name = "paper_toast",
  path = "tensorflow_third_party/paper_toast"
  
  
)

local_repository(
  name = "paper_toggle_button",
  path = "tensorflow_third_party/paper_toggle_button"
  
  
)

local_repository(
  name = "paper_toolbar",
  path = "tensorflow_third_party/paper_toolbar"
  
  
)

local_repository(
  name = "paper_tooltip",
  path = "tensorflow_third_party/paper_tooltip"
  
  
)

local_repository(
  name = "plottable",
  path = "tensorflow_third_party/plottable"
  
  
)

local_repository(
  name = "polymer",
  path = "tensorflow_third_party/polymer"
  
  
)

local_repository(
  name = "promise_polyfill",
  path = "tensorflow_third_party/promise_polyfill"
  
  
)

local_repository(
  name = "three_js_three_min_js",
  path = "tensorflow_third_party/three_js_three_min_js"
)

local_repository(
  name = "three_js_orbitcontrols_js",
  path = "tensorflow_third_party/three_js_orbitcontrols_js"
)

local_repository(
  name = "web_animations_js",
  path = "tensorflow_third_party/web_animations_js"
  
  
)

local_repository(
  name = "webcomponentsjs",
  path = "tensorflow_third_party/webcomponentsjs"
  
  
)

local_repository(
  name = "weblas_weblas_js",
  path = "tensorflow_third_party/weblas_weblas_js"
)
